export function EmptyConnectionsIllustration() {
  return (
    <svg
      viewBox="0 0 240 160"
      aria-hidden="true"
      className="w-full max-w-43"
      fill="none"
    >
      <rect
        x="30"
        y="18"
        width="180"
        height="124"
        rx="24"
        fill="currentColor"
        className="text-base-content/5"
      />
      <rect
        x="42"
        y="30"
        width="64"
        height="100"
        rx="16"
        fill="currentColor"
        className="text-base-content/10"
      />
      <rect
        x="118"
        y="30"
        width="80"
        height="100"
        rx="16"
        fill="currentColor"
        className="text-base-content/10"
      />
      <circle
        cx="28"
        cy="72"
        r="8"
        fill="currentColor"
        className="text-success/15"
      />
      <circle
        cx="214"
        cy="118"
        r="11"
        fill="currentColor"
        className="text-success/10"
      />
      <path
        d="M28 72C52 72 62 72 76 72"
        stroke="currentColor"
        className="text-success/45"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeDasharray="5 6"
      />
      <path
        d="M160 112C182 112 192 118 214 118"
        stroke="currentColor"
        className="text-success/35"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeDasharray="5 6"
      />
      <rect
        x="54"
        y="56"
        width="40"
        height="40"
        rx="14"
        fill="currentColor"
        className="text-success/12"
      />
      <path
        d="M66 76H82"
        stroke="currentColor"
        className="text-success/80"
        strokeWidth="5"
        strokeLinecap="round"
      />
      <path
        d="M74 68V84"
        stroke="currentColor"
        className="text-success/80"
        strokeWidth="5"
        strokeLinecap="round"
      />
      <rect
        x="52"
        y="106"
        width="44"
        height="6"
        rx="3"
        fill="currentColor"
        className="text-base-content/20"
      />
      <rect
        x="126"
        y="52"
        width="54"
        height="8"
        rx="4"
        fill="currentColor"
        className="text-base-content/20"
      />
      <rect
        x="126"
        y="68"
        width="40"
        height="7"
        rx="3.5"
        fill="currentColor"
        className="text-base-content/15"
      />
      <rect
        x="126"
        y="84"
        width="58"
        height="7"
        rx="3.5"
        fill="currentColor"
        className="text-base-content/15"
      />
      <rect
        x="126"
        y="102"
        width="52"
        height="10"
        rx="5"
        fill="currentColor"
        className="text-success/15"
      />
    </svg>
  );
}
