export const CONTEXT_MENU_TRANSITION_MS = 140;
export const CONNECTION_ITEM_TRANSITION_MS = 180;
export const CONNECTION_ITEM_SPACING = 2;
export const CONNECTION_ITEM_HEIGHT = 48;
export const STATUS_TRANSITION_MS = 160;
